// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dashboard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerStatus int32

const (
	ContainerStatus_UNKNOWN  ContainerStatus = 0
	ContainerStatus_STARTING ContainerStatus = 1
	ContainerStatus_RUNNING  ContainerStatus = 2
	ContainerStatus_FAILED   ContainerStatus = 3
)

// Enum value maps for ContainerStatus.
var (
	ContainerStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTING",
		2: "RUNNING",
		3: "FAILED",
	}
	ContainerStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"STARTING": 1,
		"RUNNING":  2,
		"FAILED":   3,
	}
)

func (x ContainerStatus) Enum() *ContainerStatus {
	p := new(ContainerStatus)
	*p = x
	return p
}

func (x ContainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dashboard_proto_enumTypes[0].Descriptor()
}

func (ContainerStatus) Type() protoreflect.EnumType {
	return &file_proto_dashboard_proto_enumTypes[0]
}

func (x ContainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerStatus.Descriptor instead.
func (ContainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_dashboard_proto_rawDescGZIP(), []int{0}
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_dashboard_proto_rawDescGZIP(), []int{0}
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *ListContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepositoryUrl       string                 `protobuf:"bytes,2,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	BranchOrIssue       string                 `protobuf:"bytes,3,opt,name=branch_or_issue,json=branchOrIssue,proto3" json:"branch_or_issue,omitempty"`
	Status              ContainerStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=dashboard.ContainerStatus" json:"status,omitempty"`
	LastActiveTimestamp int64                  `protobuf:"varint,5,opt,name=last_active_timestamp,json=lastActiveTimestamp,proto3" json:"last_active_timestamp,omitempty"` // Unix timestamp
	ErrorMessage        string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *Container) GetBranchOrIssue() string {
	if x != nil {
		return x.BranchOrIssue
	}
	return ""
}

func (x *Container) GetStatus() ContainerStatus {
	if x != nil {
		return x.Status
	}
	return ContainerStatus_UNKNOWN
}

func (x *Container) GetLastActiveTimestamp() int64 {
	if x != nil {
		return x.LastActiveTimestamp
	}
	return 0
}

func (x *Container) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_dashboard_proto protoreflect.FileDescriptor

const file_proto_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dashboard.proto\x12\tdashboard\"\x17\n" +
	"\x15ListContainersRequest\"N\n" +
	"\x16ListContainersResponse\x124\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x14.dashboard.ContainerR\n" +
	"containers\"\xf7\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0erepository_url\x18\x02 \x01(\tR\rrepositoryUrl\x12&\n" +
	"\x0fbranch_or_issue\x18\x03 \x01(\tR\rbranchOrIssue\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.dashboard.ContainerStatusR\x06status\x122\n" +
	"\x15last_active_timestamp\x18\x05 \x01(\x03R\x13lastActiveTimestamp\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage*E\n" +
	"\x0fContainerStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032n\n" +
	"\x10DashboardService\x12U\n" +
	"\x0eListContainers\x12 .dashboard.ListContainersRequest\x1a!.dashboard.ListContainersResponse\x1a\x03\x88\x02\x01B4Z2github.com/brotherlogic/devcontainer-manager/protob\x06proto3"

var (
	file_proto_dashboard_proto_rawDescOnce sync.Once
	file_proto_dashboard_proto_rawDescData []byte
)

func file_proto_dashboard_proto_rawDescGZIP() []byte {
	file_proto_dashboard_proto_rawDescOnce.Do(func() {
		file_proto_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dashboard_proto_rawDesc), len(file_proto_dashboard_proto_rawDesc)))
	})
	return file_proto_dashboard_proto_rawDescData
}

var file_proto_dashboard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_dashboard_proto_goTypes = []any{
	(ContainerStatus)(0),           // 0: dashboard.ContainerStatus
	(*ListContainersRequest)(nil),  // 1: dashboard.ListContainersRequest
	(*ListContainersResponse)(nil), // 2: dashboard.ListContainersResponse
	(*Container)(nil),              // 3: dashboard.Container
}
var file_proto_dashboard_proto_depIdxs = []int32{
	3, // 0: dashboard.ListContainersResponse.containers:type_name -> dashboard.Container
	0, // 1: dashboard.Container.status:type_name -> dashboard.ContainerStatus
	1, // 2: dashboard.DashboardService.ListContainers:input_type -> dashboard.ListContainersRequest
	2, // 3: dashboard.DashboardService.ListContainers:output_type -> dashboard.ListContainersResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_dashboard_proto_init() }
func file_proto_dashboard_proto_init() {
	if File_proto_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dashboard_proto_rawDesc), len(file_proto_dashboard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dashboard_proto_goTypes,
		DependencyIndexes: file_proto_dashboard_proto_depIdxs,
		EnumInfos:         file_proto_dashboard_proto_enumTypes,
		MessageInfos:      file_proto_dashboard_proto_msgTypes,
	}.Build()
	File_proto_dashboard_proto = out.File
	file_proto_dashboard_proto_goTypes = nil
	file_proto_dashboard_proto_depIdxs = nil
}
