// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_UNKNOWN_STATE   State = 0
	State_DCM_RECEIVED    State = 1
	State_DCM_CREATING    State = 2
	State_DCM_BRANCHING   State = 3
	State_DCM_HARNESS     State = 4
	State_DCM_READY       State = 5
	State_DCM_FAILED      State = 6
	State_DCM_HARD_FAILED State = 7
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "DCM_RECEIVED",
		2: "DCM_CREATING",
		3: "DCM_BRANCHING",
		4: "DCM_HARNESS",
		5: "DCM_READY",
		6: "DCM_FAILED",
		7: "DCM_HARD_FAILED",
	}
	State_value = map[string]int32{
		"UNKNOWN_STATE":   0,
		"DCM_RECEIVED":    1,
		"DCM_CREATING":    2,
		"DCM_BRANCHING":   3,
		"DCM_HARNESS":     4,
		"DCM_READY":       5,
		"DCM_FAILED":      6,
		"DCM_HARD_FAILED": 7,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_manager_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_manager_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

type UpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"` // e.g., Issue or PR number
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_proto_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

func (x *UpRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *UpRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *UpRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *UpRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type UpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DevcontainerConfig    `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpResponse) Reset() {
	*x = UpResponse{}
	mi := &file_proto_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpResponse) ProtoMessage() {}

func (x *UpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpResponse.ProtoReflect.Descriptor instead.
func (*UpResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{1}
}

func (x *UpResponse) GetConfig() *DevcontainerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownRequest) Reset() {
	*x = DownRequest{}
	mi := &file_proto_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRequest) ProtoMessage() {}

func (x *DownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRequest.ProtoReflect.Descriptor instead.
func (*DownRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{2}
}

func (x *DownRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownResponse) Reset() {
	*x = DownResponse{}
	mi := &file_proto_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownResponse) ProtoMessage() {}

func (x *DownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownResponse.ProtoReflect.Descriptor instead.
func (*DownResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{3}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*DevcontainerConfig  `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetConfigs() []*DevcontainerConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type DevcontainerConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique identifier for this devcontainer request
	Request           *UpRequest             `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"` // Original request details
	State             State                  `protobuf:"varint,3,opt,name=state,proto3,enum=manager.State" json:"state,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	InitRetryCount    int32                  `protobuf:"varint,5,opt,name=init_retry_count,json=initRetryCount,proto3" json:"init_retry_count,omitempty"`
	NextRetryTimeUnix int64                  `protobuf:"varint,6,opt,name=next_retry_time_unix,json=nextRetryTimeUnix,proto3" json:"next_retry_time_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DevcontainerConfig) Reset() {
	*x = DevcontainerConfig{}
	mi := &file_proto_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevcontainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevcontainerConfig) ProtoMessage() {}

func (x *DevcontainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevcontainerConfig.ProtoReflect.Descriptor instead.
func (*DevcontainerConfig) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{6}
}

func (x *DevcontainerConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DevcontainerConfig) GetRequest() *UpRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DevcontainerConfig) GetState() State {
	if x != nil {
		return x.State
	}
	return State_UNKNOWN_STATE
}

func (x *DevcontainerConfig) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DevcontainerConfig) GetInitRetryCount() int32 {
	if x != nil {
		return x.InitRetryCount
	}
	return 0
}

func (x *DevcontainerConfig) GetNextRetryTimeUnix() int64 {
	if x != nil {
		return x.NextRetryTimeUnix
	}
	return 0
}

var File_proto_manager_proto protoreflect.FileDescriptor

const file_proto_manager_proto_rawDesc = "" +
	"\n" +
	"\x13proto/manager.proto\x12\amanager\"o\n" +
	"\tUpRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"A\n" +
	"\n" +
	"UpResponse\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.manager.DevcontainerConfigR\x06config\"\x1d\n" +
	"\vDownRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0e\n" +
	"\fDownResponse\"\r\n" +
	"\vListRequest\"E\n" +
	"\fListResponse\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.manager.DevcontainerConfigR\aconfigs\"\xf8\x01\n" +
	"\x12DevcontainerConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\arequest\x18\x02 \x01(\v2\x12.manager.UpRequestR\arequest\x12$\n" +
	"\x05state\x18\x03 \x01(\x0e2\x0e.manager.StateR\x05state\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12(\n" +
	"\x10init_retry_count\x18\x05 \x01(\x05R\x0einitRetryCount\x12/\n" +
	"\x14next_retry_time_unix\x18\x06 \x01(\x03R\x11nextRetryTimeUnix*\x96\x01\n" +
	"\x05State\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\x10\n" +
	"\fDCM_RECEIVED\x10\x01\x12\x10\n" +
	"\fDCM_CREATING\x10\x02\x12\x11\n" +
	"\rDCM_BRANCHING\x10\x03\x12\x0f\n" +
	"\vDCM_HARNESS\x10\x04\x12\r\n" +
	"\tDCM_READY\x10\x05\x12\x0e\n" +
	"\n" +
	"DCM_FAILED\x10\x06\x12\x13\n" +
	"\x0fDCM_HARD_FAILED\x10\a2\xa9\x01\n" +
	"\x0eManagerService\x12-\n" +
	"\x02Up\x12\x12.manager.UpRequest\x1a\x13.manager.UpResponse\x123\n" +
	"\x04Down\x12\x14.manager.DownRequest\x1a\x15.manager.DownResponse\x123\n" +
	"\x04List\x12\x14.manager.ListRequest\x1a\x15.manager.ListResponseB4Z2github.com/brotherlogic/devcontainer-manager/protob\x06proto3"

var (
	file_proto_manager_proto_rawDescOnce sync.Once
	file_proto_manager_proto_rawDescData []byte
)

func file_proto_manager_proto_rawDescGZIP() []byte {
	file_proto_manager_proto_rawDescOnce.Do(func() {
		file_proto_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)))
	})
	return file_proto_manager_proto_rawDescData
}

var file_proto_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_manager_proto_goTypes = []any{
	(State)(0),                 // 0: manager.State
	(*UpRequest)(nil),          // 1: manager.UpRequest
	(*UpResponse)(nil),         // 2: manager.UpResponse
	(*DownRequest)(nil),        // 3: manager.DownRequest
	(*DownResponse)(nil),       // 4: manager.DownResponse
	(*ListRequest)(nil),        // 5: manager.ListRequest
	(*ListResponse)(nil),       // 6: manager.ListResponse
	(*DevcontainerConfig)(nil), // 7: manager.DevcontainerConfig
}
var file_proto_manager_proto_depIdxs = []int32{
	7, // 0: manager.UpResponse.config:type_name -> manager.DevcontainerConfig
	7, // 1: manager.ListResponse.configs:type_name -> manager.DevcontainerConfig
	1, // 2: manager.DevcontainerConfig.request:type_name -> manager.UpRequest
	0, // 3: manager.DevcontainerConfig.state:type_name -> manager.State
	1, // 4: manager.ManagerService.Up:input_type -> manager.UpRequest
	3, // 5: manager.ManagerService.Down:input_type -> manager.DownRequest
	5, // 6: manager.ManagerService.List:input_type -> manager.ListRequest
	2, // 7: manager.ManagerService.Up:output_type -> manager.UpResponse
	4, // 8: manager.ManagerService.Down:output_type -> manager.DownResponse
	6, // 9: manager.ManagerService.List:output_type -> manager.ListResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_manager_proto_init() }
func file_proto_manager_proto_init() {
	if File_proto_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manager_proto_goTypes,
		DependencyIndexes: file_proto_manager_proto_depIdxs,
		EnumInfos:         file_proto_manager_proto_enumTypes,
		MessageInfos:      file_proto_manager_proto_msgTypes,
	}.Build()
	File_proto_manager_proto = out.File
	file_proto_manager_proto_goTypes = nil
	file_proto_manager_proto_depIdxs = nil
}
