// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_UNKNOWN_STATE   State = 0
	State_DCM_RECEIVED    State = 1
	State_DCM_CREATING    State = 2
	State_DCM_BRANCHING   State = 3
	State_DCM_HARNESS     State = 4
	State_DCM_READY       State = 5
	State_DCM_FAILED      State = 6
	State_DCM_HARD_FAILED State = 7
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "DCM_RECEIVED",
		2: "DCM_CREATING",
		3: "DCM_BRANCHING",
		4: "DCM_HARNESS",
		5: "DCM_READY",
		6: "DCM_FAILED",
		7: "DCM_HARD_FAILED",
	}
	State_value = map[string]int32{
		"UNKNOWN_STATE":   0,
		"DCM_RECEIVED":    1,
		"DCM_CREATING":    2,
		"DCM_BRANCHING":   3,
		"DCM_HARNESS":     4,
		"DCM_READY":       5,
		"DCM_FAILED":      6,
		"DCM_HARD_FAILED": 7,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_manager_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_manager_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

type Harness int32

const (
	Harness_HARNESS_UNSPECIFIED Harness = 0
	Harness_HARNESS_ANTIGRAVITY Harness = 1
	Harness_HARNESS_PI          Harness = 2
)

// Enum value maps for Harness.
var (
	Harness_name = map[int32]string{
		0: "HARNESS_UNSPECIFIED",
		1: "HARNESS_ANTIGRAVITY",
		2: "HARNESS_PI",
	}
	Harness_value = map[string]int32{
		"HARNESS_UNSPECIFIED": 0,
		"HARNESS_ANTIGRAVITY": 1,
		"HARNESS_PI":          2,
	}
)

func (x Harness) Enum() *Harness {
	p := new(Harness)
	*p = x
	return p
}

func (x Harness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Harness) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_manager_proto_enumTypes[1].Descriptor()
}

func (Harness) Type() protoreflect.EnumType {
	return &file_proto_manager_proto_enumTypes[1]
}

func (x Harness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Harness.Descriptor instead.
func (Harness) EnumDescriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{1}
}

type ExtractionStatus int32

const (
	ExtractionStatus_EXTRACTION_UNSPECIFIED ExtractionStatus = 0
	ExtractionStatus_EXTRACTION_SUCCESS     ExtractionStatus = 1
	ExtractionStatus_EXTRACTION_FAILED      ExtractionStatus = 2
)

// Enum value maps for ExtractionStatus.
var (
	ExtractionStatus_name = map[int32]string{
		0: "EXTRACTION_UNSPECIFIED",
		1: "EXTRACTION_SUCCESS",
		2: "EXTRACTION_FAILED",
	}
	ExtractionStatus_value = map[string]int32{
		"EXTRACTION_UNSPECIFIED": 0,
		"EXTRACTION_SUCCESS":     1,
		"EXTRACTION_FAILED":      2,
	}
)

func (x ExtractionStatus) Enum() *ExtractionStatus {
	p := new(ExtractionStatus)
	*p = x
	return p
}

func (x ExtractionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtractionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_manager_proto_enumTypes[2].Descriptor()
}

func (ExtractionStatus) Type() protoreflect.EnumType {
	return &file_proto_manager_proto_enumTypes[2]
}

func (x ExtractionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtractionStatus.Descriptor instead.
func (ExtractionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{2}
}

type Identifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*Identifier_IssueNumber
	//	*Identifier_PrNumber
	Id            isIdentifier_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_proto_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Identifier) GetId() isIdentifier_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Identifier) GetIssueNumber() int32 {
	if x != nil {
		if x, ok := x.Id.(*Identifier_IssueNumber); ok {
			return x.IssueNumber
		}
	}
	return 0
}

func (x *Identifier) GetPrNumber() int32 {
	if x != nil {
		if x, ok := x.Id.(*Identifier_PrNumber); ok {
			return x.PrNumber
		}
	}
	return 0
}

type isIdentifier_Id interface {
	isIdentifier_Id()
}

type Identifier_IssueNumber struct {
	IssueNumber int32 `protobuf:"varint,1,opt,name=issue_number,json=issueNumber,proto3,oneof"`
}

type Identifier_PrNumber struct {
	PrNumber int32 `protobuf:"varint,2,opt,name=pr_number,json=prNumber,proto3,oneof"`
}

func (*Identifier_IssueNumber) isIdentifier_Id() {}

func (*Identifier_PrNumber) isIdentifier_Id() {}

type UpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Identifier    *Identifier            `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"` // e.g., Issue or PR number
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Harness       Harness                `protobuf:"varint,6,opt,name=harness,proto3,enum=manager.Harness" json:"harness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_proto_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{1}
}

func (x *UpRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *UpRequest) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UpRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *UpRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpRequest) GetHarness() Harness {
	if x != nil {
		return x.Harness
	}
	return Harness_HARNESS_UNSPECIFIED
}

type UpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DevcontainerConfig    `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpResponse) Reset() {
	*x = UpResponse{}
	mi := &file_proto_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpResponse) ProtoMessage() {}

func (x *UpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpResponse.ProtoReflect.Descriptor instead.
func (*UpResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{2}
}

func (x *UpResponse) GetConfig() *DevcontainerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownRequest) Reset() {
	*x = DownRequest{}
	mi := &file_proto_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRequest) ProtoMessage() {}

func (x *DownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRequest.ProtoReflect.Descriptor instead.
func (*DownRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{3}
}

func (x *DownRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownResponse) Reset() {
	*x = DownResponse{}
	mi := &file_proto_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownResponse) ProtoMessage() {}

func (x *DownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownResponse.ProtoReflect.Descriptor instead.
func (*DownResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{4}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{5}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*DevcontainerConfig  `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetConfigs() []*DevcontainerConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type PushPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPromptRequest) Reset() {
	*x = PushPromptRequest{}
	mi := &file_proto_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPromptRequest) ProtoMessage() {}

func (x *PushPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPromptRequest.ProtoReflect.Descriptor instead.
func (*PushPromptRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{7}
}

func (x *PushPromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PushPromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type PushPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPromptResponse) Reset() {
	*x = PushPromptResponse{}
	mi := &file_proto_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPromptResponse) ProtoMessage() {}

func (x *PushPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPromptResponse.ProtoReflect.Descriptor instead.
func (*PushPromptResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{8}
}

type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTokens   int64                  `protobuf:"varint,1,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Status        ExtractionStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=manager.ExtractionStatus" json:"status,omitempty"`
	FailureReason string                 `protobuf:"bytes,3,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_proto_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{9}
}

func (x *TokenUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TokenUsage) GetStatus() ExtractionStatus {
	if x != nil {
		return x.Status
	}
	return ExtractionStatus_EXTRACTION_UNSPECIFIED
}

func (x *TokenUsage) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type DevcontainerConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique identifier for this devcontainer request
	Request           *UpRequest             `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"` // Original request details
	State             State                  `protobuf:"varint,3,opt,name=state,proto3,enum=manager.State" json:"state,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	InitRetryCount    int32                  `protobuf:"varint,5,opt,name=init_retry_count,json=initRetryCount,proto3" json:"init_retry_count,omitempty"`
	NextRetryTimeUnix int64                  `protobuf:"varint,6,opt,name=next_retry_time_unix,json=nextRetryTimeUnix,proto3" json:"next_retry_time_unix,omitempty"`
	TokenUsage        *TokenUsage            `protobuf:"bytes,7,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DevcontainerConfig) Reset() {
	*x = DevcontainerConfig{}
	mi := &file_proto_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevcontainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevcontainerConfig) ProtoMessage() {}

func (x *DevcontainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevcontainerConfig.ProtoReflect.Descriptor instead.
func (*DevcontainerConfig) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{10}
}

func (x *DevcontainerConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DevcontainerConfig) GetRequest() *UpRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DevcontainerConfig) GetState() State {
	if x != nil {
		return x.State
	}
	return State_UNKNOWN_STATE
}

func (x *DevcontainerConfig) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DevcontainerConfig) GetInitRetryCount() int32 {
	if x != nil {
		return x.InitRetryCount
	}
	return 0
}

func (x *DevcontainerConfig) GetNextRetryTimeUnix() int64 {
	if x != nil {
		return x.NextRetryTimeUnix
	}
	return 0
}

func (x *DevcontainerConfig) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

var File_proto_manager_proto protoreflect.FileDescriptor

const file_proto_manager_proto_rawDesc = "" +
	"\n" +
	"\x13proto/manager.proto\x12\amanager\"V\n" +
	"\n" +
	"Identifier\x12#\n" +
	"\fissue_number\x18\x01 \x01(\x05H\x00R\vissueNumber\x12\x1d\n" +
	"\tpr_number\x18\x02 \x01(\x05H\x00R\bprNumberB\x04\n" +
	"\x02id\"\xc6\x01\n" +
	"\tUpRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x123\n" +
	"\n" +
	"identifier\x18\x02 \x01(\v2\x13.manager.IdentifierR\n" +
	"identifier\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12*\n" +
	"\aharness\x18\x06 \x01(\x0e2\x10.manager.HarnessR\aharness\"A\n" +
	"\n" +
	"UpResponse\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.manager.DevcontainerConfigR\x06config\"\x1d\n" +
	"\vDownRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0e\n" +
	"\fDownResponse\"\r\n" +
	"\vListRequest\"E\n" +
	"\fListResponse\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.manager.DevcontainerConfigR\aconfigs\";\n" +
	"\x11PushPromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"\x14\n" +
	"\x12PushPromptResponse\"\x89\x01\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\ftotal_tokens\x18\x01 \x01(\x03R\vtotalTokens\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.manager.ExtractionStatusR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x03 \x01(\tR\rfailureReason\"\xae\x02\n" +
	"\x12DevcontainerConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\arequest\x18\x02 \x01(\v2\x12.manager.UpRequestR\arequest\x12$\n" +
	"\x05state\x18\x03 \x01(\x0e2\x0e.manager.StateR\x05state\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12(\n" +
	"\x10init_retry_count\x18\x05 \x01(\x05R\x0einitRetryCount\x12/\n" +
	"\x14next_retry_time_unix\x18\x06 \x01(\x03R\x11nextRetryTimeUnix\x124\n" +
	"\vtoken_usage\x18\a \x01(\v2\x13.manager.TokenUsageR\n" +
	"tokenUsage*\x96\x01\n" +
	"\x05State\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\x10\n" +
	"\fDCM_RECEIVED\x10\x01\x12\x10\n" +
	"\fDCM_CREATING\x10\x02\x12\x11\n" +
	"\rDCM_BRANCHING\x10\x03\x12\x0f\n" +
	"\vDCM_HARNESS\x10\x04\x12\r\n" +
	"\tDCM_READY\x10\x05\x12\x0e\n" +
	"\n" +
	"DCM_FAILED\x10\x06\x12\x13\n" +
	"\x0fDCM_HARD_FAILED\x10\a*K\n" +
	"\aHarness\x12\x17\n" +
	"\x13HARNESS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HARNESS_ANTIGRAVITY\x10\x01\x12\x0e\n" +
	"\n" +
	"HARNESS_PI\x10\x02*]\n" +
	"\x10ExtractionStatus\x12\x1a\n" +
	"\x16EXTRACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EXTRACTION_SUCCESS\x10\x01\x12\x15\n" +
	"\x11EXTRACTION_FAILED\x10\x022\xf0\x01\n" +
	"\x0eManagerService\x12-\n" +
	"\x02Up\x12\x12.manager.UpRequest\x1a\x13.manager.UpResponse\x123\n" +
	"\x04Down\x12\x14.manager.DownRequest\x1a\x15.manager.DownResponse\x123\n" +
	"\x04List\x12\x14.manager.ListRequest\x1a\x15.manager.ListResponse\x12E\n" +
	"\n" +
	"PushPrompt\x12\x1a.manager.PushPromptRequest\x1a\x1b.manager.PushPromptResponseB4Z2github.com/brotherlogic/devcontainer-manager/protob\x06proto3"

var (
	file_proto_manager_proto_rawDescOnce sync.Once
	file_proto_manager_proto_rawDescData []byte
)

func file_proto_manager_proto_rawDescGZIP() []byte {
	file_proto_manager_proto_rawDescOnce.Do(func() {
		file_proto_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)))
	})
	return file_proto_manager_proto_rawDescData
}

var file_proto_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_manager_proto_goTypes = []any{
	(State)(0),                 // 0: manager.State
	(Harness)(0),               // 1: manager.Harness
	(ExtractionStatus)(0),      // 2: manager.ExtractionStatus
	(*Identifier)(nil),         // 3: manager.Identifier
	(*UpRequest)(nil),          // 4: manager.UpRequest
	(*UpResponse)(nil),         // 5: manager.UpResponse
	(*DownRequest)(nil),        // 6: manager.DownRequest
	(*DownResponse)(nil),       // 7: manager.DownResponse
	(*ListRequest)(nil),        // 8: manager.ListRequest
	(*ListResponse)(nil),       // 9: manager.ListResponse
	(*PushPromptRequest)(nil),  // 10: manager.PushPromptRequest
	(*PushPromptResponse)(nil), // 11: manager.PushPromptResponse
	(*TokenUsage)(nil),         // 12: manager.TokenUsage
	(*DevcontainerConfig)(nil), // 13: manager.DevcontainerConfig
}
var file_proto_manager_proto_depIdxs = []int32{
	3,  // 0: manager.UpRequest.identifier:type_name -> manager.Identifier
	1,  // 1: manager.UpRequest.harness:type_name -> manager.Harness
	13, // 2: manager.UpResponse.config:type_name -> manager.DevcontainerConfig
	13, // 3: manager.ListResponse.configs:type_name -> manager.DevcontainerConfig
	2,  // 4: manager.TokenUsage.status:type_name -> manager.ExtractionStatus
	4,  // 5: manager.DevcontainerConfig.request:type_name -> manager.UpRequest
	0,  // 6: manager.DevcontainerConfig.state:type_name -> manager.State
	12, // 7: manager.DevcontainerConfig.token_usage:type_name -> manager.TokenUsage
	4,  // 8: manager.ManagerService.Up:input_type -> manager.UpRequest
	6,  // 9: manager.ManagerService.Down:input_type -> manager.DownRequest
	8,  // 10: manager.ManagerService.List:input_type -> manager.ListRequest
	10, // 11: manager.ManagerService.PushPrompt:input_type -> manager.PushPromptRequest
	5,  // 12: manager.ManagerService.Up:output_type -> manager.UpResponse
	7,  // 13: manager.ManagerService.Down:output_type -> manager.DownResponse
	9,  // 14: manager.ManagerService.List:output_type -> manager.ListResponse
	11, // 15: manager.ManagerService.PushPrompt:output_type -> manager.PushPromptResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_manager_proto_init() }
func file_proto_manager_proto_init() {
	if File_proto_manager_proto != nil {
		return
	}
	file_proto_manager_proto_msgTypes[0].OneofWrappers = []any{
		(*Identifier_IssueNumber)(nil),
		(*Identifier_PrNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manager_proto_goTypes,
		DependencyIndexes: file_proto_manager_proto_depIdxs,
		EnumInfos:         file_proto_manager_proto_enumTypes,
		MessageInfos:      file_proto_manager_proto_msgTypes,
	}.Build()
	File_proto_manager_proto = out.File
	file_proto_manager_proto_goTypes = nil
	file_proto_manager_proto_depIdxs = nil
}
